CREATE DATABASE engineering_db;

USE engineering_db;

CREATE TABLE applications (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(15) NOT NULL,
gender VARCHAR(10) NOT NULL,
dob DATE NOT NULL,
branch VARCHAR(50) NOT NULL,
address TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
